touch_driver:
  ros__parameters:
    device_name: Default Device
    publish_rate_hz: 250.0
    controller_plugin: touch_controllers/ImpedanceController
    # controller_plugin: touch_controllers/NullController
    max_force: 1.0
    impedance_stiffness: [45.0, 45.0, 45.0]
    impedance_damping: [1.0, 1.0, 1.0]
