controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    touch_force_controller:
      type: gpio_controllers/GpioCommandController

    touch_pose_broadcaster:
      type: pose_broadcaster/PoseBroadcaster

touch_force_controller:
  ros__parameters:
    gpios:
      - force
    command_interfaces:
      force:
        - interfaces:
          - force.x
          - force.y
          - force.z

touch_pose_broadcaster:
  ros__parameters:
    pose_name: tcp_pose
    frame_id: touch_base
    tf.enable: true
    tf.child_frame_id: touch_tcp
